packages:
  - 'apps/*'

minimumReleaseAgeExclude:
  - '@analogjs/vite-plugin-angular@2.6.0'
  - '@analogjs/vitest-angular@2.6.0'
  - '@angular-devkit/architect@0.2200.0'
  - '@angular-devkit/build-angular@22.0.0'
  - '@angular-devkit/build-webpack@0.2200.0'
  - '@angular-devkit/core@22.0.0'
  - '@angular-devkit/schematics@22.0.0'
  - '@angular/animations@22.0.0'
  - '@angular/build@22.0.0'
  - '@angular/cdk@22.0.0'
  - '@angular/cli@22.0.0'
  - '@angular/common@22.0.0'
  - '@angular/compiler-cli@22.0.0'
  - '@angular/compiler@22.0.0'
  - '@angular/core@22.0.0'
  - '@angular/forms@22.0.0'
  - '@angular/material@22.0.0'
  - '@angular/platform-browser-dynamic@22.0.0'
  - '@angular/platform-browser@22.0.0'
  - '@angular/router@22.0.0'
  - '@gurezo/web-serial-rxjs@2.3.3'
  - '@inquirer/editor@5.2.2'
  - '@inquirer/external-editor@3.0.3'
  - '@inquirer/input@5.1.2'
  - '@jsonjoy.com/fs-core@4.57.6'
  - '@jsonjoy.com/fs-fsa@4.57.6'
  - '@jsonjoy.com/fs-node-builtins@4.57.6'
  - '@jsonjoy.com/fs-node-to-fsa@4.57.6'
  - '@jsonjoy.com/fs-node-utils@4.57.6'
  - '@jsonjoy.com/fs-node@4.57.6'
  - '@jsonjoy.com/fs-print@4.57.6'
  - '@jsonjoy.com/fs-snapshot@4.57.6'
  - '@ngtools/webpack@22.0.0'
  - '@nx/angular@22.7.5'
  - '@nx/devkit@22.7.5'
  - '@nx/eslint-plugin@22.7.5'
  - '@nx/eslint@22.7.5'
  - '@nx/js@22.7.5'
  - '@nx/module-federation@22.7.5'
  - '@nx/nx-darwin-arm64@22.7.5'
  - '@nx/nx-darwin-x64@22.7.5'
  - '@nx/nx-freebsd-x64@22.7.5'
  - '@nx/nx-linux-arm-gnueabihf@22.7.5'
  - '@nx/nx-linux-arm64-gnu@22.7.5'
  - '@nx/nx-linux-arm64-musl@22.7.5'
  - '@nx/nx-linux-x64-gnu@22.7.5'
  - '@nx/nx-linux-x64-musl@22.7.5'
  - '@nx/nx-win32-arm64-msvc@22.7.5'
  - '@nx/nx-win32-x64-msvc@22.7.5'
  - '@nx/rspack@22.7.5'
  - '@nx/vite@22.7.5'
  - '@nx/vitest@22.7.5'
  - '@nx/web@22.7.5'
  - '@nx/webpack@22.7.5'
  - '@nx/workspace@22.7.5'
  - '@schematics/angular@22.0.0'
  - '@swc/helpers@0.5.23'
  - '@testing-library/angular@19.4.1'
  - '@types/node@25.9.2'
  - '@typescript-eslint/eslint-plugin@8.60.1'
  - '@typescript-eslint/project-service@8.60.1'
  - '@typescript-eslint/scope-manager@8.60.1'
  - '@typescript-eslint/tsconfig-utils@8.60.1'
  - '@typescript-eslint/type-utils@8.60.1'
  - '@typescript-eslint/types@8.60.1'
  - '@typescript-eslint/typescript-estree@8.60.1'
  - '@typescript-eslint/utils@8.60.1'
  - '@typescript-eslint/visitor-keys@8.60.1'
  - '@vitest/coverage-v8@4.1.8'
  - '@vitest/expect@4.1.8'
  - '@vitest/mocker@4.1.8'
  - '@vitest/pretty-format@4.1.8'
  - '@vitest/runner@4.1.8'
  - '@vitest/snapshot@4.1.8'
  - '@vitest/spy@4.1.8'
  - '@vitest/ui@4.1.8'
  - '@vitest/utils@4.1.8'
  - 'memfs@4.57.6'
  - 'nx@22.7.5'
  - 'tinyglobby@0.2.17'
  - 'tmp@0.2.6'
  - 'typescript@6.0.3'
  - 'vite@8.0.16'
  - 'vitest@4.1.8'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx

# Malicious releases are often detected and removed within a week.
# 7 days x 24h x 60 min
minimumReleaseAge: 10080
