packages:
  - 'apps/*'

minimumReleaseAgeExclude:
  - '@swc/core-darwin-arm64@1.15.40'
  - '@swc/core-darwin-x64@1.15.40'
  - '@swc/core-linux-arm-gnueabihf@1.15.40'
  - '@swc/core-linux-arm64-gnu@1.15.40'
  - '@swc/core-linux-arm64-musl@1.15.40'
  - '@swc/core-linux-ppc64-gnu@1.15.40'
  - '@swc/core-linux-s390x-gnu@1.15.40'
  - '@swc/core-linux-x64-gnu@1.15.40'
  - '@swc/core-linux-x64-musl@1.15.40'
  - '@swc/core-win32-arm64-msvc@1.15.40'
  - '@swc/core-win32-ia32-msvc@1.15.40'
  - '@swc/core-win32-x64-msvc@1.15.40'
  - '@swc/core@1.15.40'
  - '@testing-library/angular@19.3.0'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx

# Malicious releases are often detected and removed within a week.
# 7 days x 24h x 60 min
# minimumReleaseAge: 10080
